/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        background: "#f9f9f9",
        "primary-container": "#1b1b1b",
        "on-secondary-fixed": "#001b3f",
        "surface-container-low": "#f3f3f3",
        "surface-bright": "#f9f9f9",
        primary: "#000000",
        "on-surface": "#1b1b1b",
        tertiary: "#000000",
        "on-tertiary-fixed-variant": "#474747",
        error: "#ba1a1a",
        "surface-container": "#eeeeee",
        "on-primary": "#ffffff",
        "on-primary-container": "#848484",
        "inverse-on-surface": "#f1f1f1",
        "secondary-fixed-dim": "#abc7ff",
        "on-primary-fixed-variant": "#474747",
        "primary-fixed-dim": "#c6c6c6",
        outline: "#7e7576",
        "inverse-primary": "#c6c6c6",
        "on-background": "#1b1b1b",
        "on-error-container": "#93000a",
        "inverse-surface": "#303030",
        "secondary-fixed": "#d7e3ff",
        surface: "#f9f9f9",
        "outline-variant": "#cfc4c5",
        "system-grey-light": "#86868B",
        "secondary-container": "#619dff",
        "apple-blue": "#0066CC",
        "on-secondary-fixed-variant": "#00458f",
        "error-container": "#ffdad6",
        "system-grey-dark": "#1D1D1F",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "surface-tint": "#5e5e5e",
        "surface-background": "#FFFFFF",
        secondary: "#015cba",
        "surface-variant": "#e2e2e2",
        "tertiary-container": "#1b1b1b",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-container-high": "#e8e8e8",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#4c4546",
        "on-tertiary-container": "#848484",
        "surface-dim": "#dadada",
        "on-secondary-container": "#00346e",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "20px",
        "margin-desktop": "30px",
        "base-unit": "8px",
        "section-gap-sm": "80px",
        "margin-mobile": "20px",
        "section-gap-lg": "120px",
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.33", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["36px", { lineHeight: "1.1", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md-mobile": ["28px", { lineHeight: "1.15", letterSpacing: "0.004em", fontWeight: "600" }],
        "body-lg": ["21px", { lineHeight: "1.38", letterSpacing: "0.011em", fontWeight: "400" }],
        "body-md": ["17px", { lineHeight: "1.47", letterSpacing: "-0.022em", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "1.1", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
